// APMO Countries Data - Static data from CSV
export const countriesData = [
  { code: 'ARG', country: 'Argentina', status: 'Active', representative: '' },
  { code: 'AUS', country: 'Australia', status: 'Active', representative: '' },
  { code: 'AZE', country: 'Azerbaijan', status: '', representative: '' },
  { code: 'BGD', country: 'Bangladesh', status: 'Active', representative: '' },
  { code: 'BOL', country: 'Bolivia', status: 'Active', representative: '' },
  { code: 'BRA', country: 'Brazil', status: 'Active', representative: '' },
  { code: 'BGR', country: 'Bulgaria', status: 'Active', representative: '' },
  { code: 'KHM', country: 'Cambodia', status: 'Active', representative: '' },
  { code: 'CAN', country: 'Canada', status: 'Active', representative: '' },
  { code: 'CHL', country: 'Chile', status: '', representative: '' },
  { code: 'COL', country: 'Colombia', status: 'Active', representative: '' },
  { code: 'CRI', country: 'Costa Rica', status: 'Active', representative: '' },
  { code: 'CIV', country: "Côte d'Ivoire", status: '', representative: '' },
  { code: 'ECU', country: 'Ecuador', status: 'Active', representative: '' },
  { code: 'SLV', country: 'El Salvador', status: 'Active', representative: '' },
  { code: 'GTM', country: 'Guatemala', status: 'Active', representative: '' },
  { code: 'HKG', country: 'Hong Kong', status: 'Active', representative: '' },
  { code: 'IND', country: 'India', status: 'Active', representative: '' },
  { code: 'IDN', country: 'Indonesia', status: 'Active', representative: '' },
  {
    code: 'IRN',
    country: 'Islamic Republic of Iran',
    status: 'Active',
    representative: '',
  },
  { code: 'JPN', country: 'Japan', status: 'Active', representative: '' },
  { code: 'KAZ', country: 'Kazakhstan', status: 'Active', representative: '' },
  { code: 'KGZ', country: 'Kyrgyzstan', status: 'Active', representative: '' },
  { code: 'MAC', country: 'Macau', status: 'Active', representative: '' },
  { code: 'MKD', country: 'Macedonia', status: 'Active', representative: '' },
  { code: 'MYS', country: 'Malaysia', status: 'Active', representative: '' },
  { code: 'MEX', country: 'Mexico', status: 'Active', representative: '' },
  { code: 'MAR', country: 'Morocco', status: 'Active', representative: '' },
  { code: 'NZL', country: 'New Zealand', status: 'Active', representative: '' },
  { code: 'NIC', country: 'Nicaragua', status: 'Active', representative: '' },
  { code: 'PAK', country: 'Pakistan', status: 'Active', representative: '' },
  { code: 'PAN', country: 'Panama', status: 'Active', representative: '' },
  { code: 'PER', country: 'Peru', status: 'Active', representative: '' },
  { code: 'PHL', country: 'Philippines', status: 'Active', representative: '' },
  { code: 'QAT', country: 'Qatar', status: '', representative: '' },
  {
    code: 'KOR',
    country: 'Republic of Korea',
    status: 'Active',
    representative: '',
  },
  { code: 'RUS', country: 'Russia', status: 'Active', representative: '' },
  { code: 'RWA', country: 'Rwanda', status: 'Active', representative: '' },
  {
    code: 'SAU',
    country: 'Saudi Arabia',
    status: 'Active',
    representative: '',
  },
  { code: 'SGP', country: 'Singapore', status: 'Active', representative: '' },
  { code: 'LKA', country: 'Sri Lanka', status: 'Active', representative: '' },
  { code: 'SYR', country: 'Syria', status: 'Active', representative: '' },
  { code: 'TWN', country: 'Taiwan', status: 'Active', representative: '' },
  { code: 'TJK', country: 'Tajikistan', status: 'Active', representative: '' },
  { code: 'THA', country: 'Thailand', status: 'Active', representative: '' },
  {
    code: 'TTO',
    country: 'Trinidad and Tobago',
    status: 'Active',
    representative: '',
  },
  {
    code: 'TKM',
    country: 'Turkmenistan',
    status: 'Active',
    representative: '',
  },
  {
    code: 'ARE',
    country: 'United Arab Emirates',
    status: 'Active',
    representative: '',
  },
  {
    code: 'USA',
    country: 'United States of America',
    status: 'Active',
    representative: '',
  },
  { code: 'URY', country: 'Uruguay', status: 'Active', representative: '' },
  { code: 'UZB', country: 'Uzbekistan', status: 'Active', representative: '' },
];
