/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/product": {
    /** Product Package List */
    get: operations["product_package_list_product_get"];
  };
  "/product/product_detail": {
    /** Get Product Package Detail */
    get: operations["get_product_package_detail_product_product_detail_get"];
  };
  "/user/login": {
    /** Users Login */
    post: operations["users_login_user_login_post"];
  };
  "/user/me": {
    /** Get User Info From Access Token */
    get: operations["get_user_info_from_access_token_user_me_get"];
  };
  "/user/change-password": {
    /** Users Change Password */
    post: operations["users_change_password_user_change_password_post"];
  };
  "/user/refresh-token": {
    /** Users Refresh Token */
    post: operations["users_refresh_token_user_refresh_token_post"];
  };
  "/user/register": {
    /** Users Register */
    post: operations["users_register_user_register_post"];
  };
  "/user/update": {
    /** Users Update */
    post: operations["users_update_user_update_post"];
  };
  "/user/forget-password": {
    /** Forget Password */
    post: operations["forget_password_user_forget_password_post"];
  };
  "/user/search-by-exam-number": {
    /** Search By Exam Number */
    get: operations["search_by_exam_number_user_search_by_exam_number_get"];
  };
  "/user/get-avatar-link": {
    /** Get Avatar Link */
    get: operations["get_avatar_link_user_get_avatar_link_get"];
  };
  "/user/register-captcha": {
    /** Users Register With Captcha */
    post: operations["users_register_with_captcha_user_register_captcha_post"];
  };
  "/user/forget-password-captcha": {
    /** Forget Password Captcha */
    post: operations["forget_password_captcha_user_forget_password_captcha_post"];
  };
  "/user/search-es-exam-number": {
    /** Search Elastic Exam Number */
    get: operations["search_elastic_exam_number_user_search_es_exam_number_get"];
  };
  "/common/ping": {
    /** Api Ping */
    get: operations["api_ping_common_ping_get"];
  };
  "/common/get_countries": {
    /** Get Countries */
    get: operations["get_countries_common_get_countries_get"];
  };
  "/common/get_ethnics": {
    /** Get Ethnics */
    get: operations["get_ethnics_common_get_ethnics_get"];
  };
  "/common/get_provinces": {
    /** Get Provinces */
    get: operations["get_provinces_common_get_provinces_get"];
  };
  "/common/get_districts": {
    /** Get Districts */
    get: operations["get_districts_common_get_districts_get"];
  };
  "/common/get_schools": {
    /** Get Schools */
    get: operations["get_schools_common_get_schools_get"];
  };
  "/common/get_prefix_media_url": {
    /** Get Prefix Media Url */
    get: operations["get_prefix_media_url_common_get_prefix_media_url_get"];
  };
  "/payment/callback": {
    /** Callback */
    post: operations["callback_payment_callback_post"];
  };
  "/payment": {
    /** Create Payment Transaction */
    post: operations["create_payment_transaction_payment_post"];
  };
  "/payment/remove_item": {
    /** Remove Item */
    post: operations["remove_item_payment_remove_item_post"];
  };
  "/payment/verify": {
    /** Verify Payment */
    post: operations["verify_payment_payment_verify_post"];
  };
  "/payment/order": {
    /** Create Payment Order */
    post: operations["create_payment_order_payment_order_post"];
  };
  "/payment{tran_id}": {
    /** Detail Payment Transaction */
    get: operations["detail_payment_transaction_payment_tran_id__get"];
  };
  "/cart/{cart_id}": {
    /** Get Details */
    get: operations["get_details_cart__cart_id__get"];
  };
  "/cart/remove_item": {
    /** Remove Item */
    post: operations["remove_item_cart_remove_item_post"];
  };
  "/cart/add_item": {
    /** Add To Cart */
    post: operations["add_to_cart_cart_add_item_post"];
  };
  "/voucher/verify/{code}": {
    /** Verify Voucher */
    get: operations["verify_voucher_voucher_verify__code__get"];
  };
  "/voucher/apply": {
    /** Apply Voucher */
    post: operations["apply_voucher_voucher_apply_post"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AddItemToCartParams */
    AddItemToCartParams: {
      /**
       * Định danh gói sản phẩm 
       * @default
       */
      product_package_id?: string;
      /**
       * Định danh giỏ hàng(Nếu trường này có dữ liệu trong localstorage là add vào item vào cart_id này. NULL là tạo mới cart) 
       * @default
       */
      cart_id?: string;
      /**
       * Danh sách học viên được mua hộ 
       * @default []
       */
      students?: (components["schemas"]["UserByIDOrName"])[];
    };
    /** AddItemToCartResp */
    AddItemToCartResp: {
      /**
       * Định danh giỏ hàng(Nếu định danh giỏ hàng chưa có trong localstorage thì lưu lại) 
       * @default
       */
      cart_id?: string;
      /**
       * Tổng tiền thanh toán 
       * @default 0
       */
      total_amount?: number;
      /** Danh sách gói sản phẩm */
      product_packages: (components["schemas"]["ProductPackageResponse"])[];
    };
    /** ApplyVoucherReq */
    ApplyVoucherReq: {
      /** Mã voucher */
      code: string;
      /** Định danh gói */
      product_package_id: string;
      /** Định danh giao dịch */
      product_transaction_id: string;
    };
    /** CartDetailReps */
    CartDetailReps: {
      /** Định danh giỏ hàng */
      cart_id: string;
      /**
       * Tổng tiền thanh toán 
       * @default 0
       */
      total_amount?: number;
      /** Danh sách gói sản phẩm */
      product_packages: (components["schemas"]["ProductPackageResponse"])[];
    };
    /** CreatePaymentRequest */
    CreatePaymentRequest: {
      /**
       * Định danh giỏ hàng, định danh này được lưu phía client. Chỉ khi thanh toán qua giỏ hàng thì có định danh này 
       * @default
       */
      cart_id?: string;
      /** Danh sách package mà người mua */
      product_packages: (components["schemas"]["ProductPackageRequest"])[];
    };
    /** CreatePaymentResp */
    CreatePaymentResp: {
      /**
       * Định danh của một giao dịch thanh toán 
       * @default
       */
      product_transaction_id?: string;
      /**
       * Tổng tiền thanh toán 
       * @default 0
       */
      total_amount?: number;
      /**
       * Danh sách gói sản phẩm 
       * @default []
       */
      product_packages?: (components["schemas"]["ProductPackageResponse"])[];
      /**
       * Tổng tiền được giảm từ voucher 
       * @default 0
       */
      total_voucher_amount?: number;
      /**
       * Định danh giỏ hàng, định danh này được lưu phía client. Chỉ khi thanh toán qua giỏ hàng thì có định danh này 
       * @default
       */
      cart_id?: string;
    };
    /** DetailPaymentTransaction */
    DetailPaymentTransaction: {
      /** Định danh giao dịch */
      product_transaction_id: string;
      /** Người thanh toán */
      payer_id: string;
      /** Tên người thanh toán */
      payer_name?: string;
      /** Giỏ hàng id, giỏ hàng này được lưu phía client */
      cart_id?: string;
      /** Tổng giá trị thanh toán */
      total_amount?: number;
      /** Danh sách package */
      product_packages: (components["schemas"]["PaymentProductPackage"])[];
      pay_info?: components["schemas"]["PayInfo"];
      /** 1: Chờ xác nhận; 2: đã xác nhận; 3: chờ thanh toán; 4: đã thanh toán; 5: đã hủy; 6: thanh toán thất bại */
      status: number;
      /**
       * Tổng tiền được giảm từ voucher 
       * @default 0
       */
      total_voucher_amount?: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: (components["schemas"]["ValidationError"])[];
    };
    /** ListProductPackagesResp */
    ListProductPackagesResp: {
      /** Định danh sản phẩm */
      product_package_id: string;
      /** Nhóm các gói sản phẩm TRANG_NGUYEN_TIENG_VIET, TRANG_NGUYEN_TOAN_TAI, TRANG_NGUYEN_LICH_SU, TRUONG_HOC_TRUC_TUYEN, CONG_NGHE_GIAO_DUC */
      group_name: string;
      /** Cấp độ giá trị từ 1 - 12 */
      level: number;
      /** Thông tin mô tả sản phẩm */
      info: string;
      /** Giá tiền sản phẩm */
      price: number;
      /** Đơn vị tiền tệ */
      monetary_unit: string;
      /** Tên sản phẩm */
      product_package_name: string;
      /** Thời hạn hiệu lực: 0 là không thời hạn (trọn đời); n là n tháng */
      limitation: number;
      /** Điểm đánh giá chỉ nằm từ 1 - 5 */
      review_point: number;
      /** number_of_reviewers */
      number_of_reviewers: number;
      /** number_of_users */
      number_of_users: number;
      /** icon_link */
      icon_link: string;
    };
    /** PayInfo */
    PayInfo: {
      /** Name */
      name?: string;
      /** Phone Number */
      phone_number?: string;
      /** Email */
      email?: string;
    };
    /** PaymentCallRequest */
    PaymentCallRequest: {
      /** amount */
      amount: number;
      /**
       * Phía gateway trả về duy nhất cho mỗi giao dịch 
       * @default
       */
      service_request_id?: string;
      /**
       * extra_data 
       * @default
       */
      extra_data?: string;
      /**
       * partner_code 
       * @default
       */
      partner_code?: string;
      /**
       * ref_order_id 
       * @default
       */
      ref_order_id?: string;
      /**
       * response_time 
       * @default
       */
      response_time?: string;
      /**
       * service_code 
       * @default
       */
      service_code?: string;
      /**
       * success 
       * @default 0
       */
      status?: number;
      /**
       * signature 
       * @default
       */
      signature?: string;
    };
    /** PaymentOrderRequest */
    PaymentOrderRequest: {
      /**
       * Phương thức thanh toán(1: VNPAY_QR_IN, 2: VNPAY_ATM_IN, 3: VNPAY_CC_IN) 
       * @default 2
       */
      payment_method?: number;
      /**
       * Định danh của một giao dịch thanh toán 
       * @default
       */
      product_transaction_id?: string;
      /**
       * Url muốn chuyển hướng đến sau khi khách hàng thanh toán thành công 
       * @default
       */
      url_redirect?: string;
    };
    /** PaymentOrderResp */
    PaymentOrderResp: {
      /**
       * Định danh của một giao dịch thanh toán 
       * @default
       */
      product_transaction_id?: string;
      /**
       * Đường link thanh toán 
       * @default
       */
      pay_url?: string;
    };
    /** PaymentProductPackage */
    PaymentProductPackage: {
      /** Product Package Id */
      product_package_id?: string;
      /** Cart Item Id */
      cart_item_id?: string;
      /** Product Package Name */
      product_package_name?: string;
      /** Price */
      price?: string;
      /** Monetary Unit */
      monetary_unit?: string;
      /** Voucher Id */
      voucher_id?: string;
      /** Voucher Code */
      voucher_code?: string;
      /** Voucher Monetary Unit */
      voucher_monetary_unit?: string;
      /** Voucher Value */
      voucher_value?: string;
      /** User Names List */
      user_names_list?: (components["schemas"]["UserByIDOrName"])[];
      /**
       * Tổng tiền theo từng gói sản phẩm 
       * @default 0
       */
      package_total_amount?: number;
    };
    /** ProductPackageRequest */
    ProductPackageRequest: {
      /**
       * Định danh gói sản phẩm 
       * @default
       */
      product_package_id?: string;
      /**
       * Danh sách định danh học viên được mua hộ 
       * @default []
       */
      users?: (string)[];
      /**
       * Nếu click thanh toán từ giỏ hàng thì có thêm thông tin này 
       * @default
       */
      cart_item_id?: string;
    };
    /** ProductPackageResponse */
    ProductPackageResponse: {
      /**
       * Định danh gói sản phẩm 
       * @default
       */
      product_package_id?: string;
      /**
       * Tên gói sản phẩm 
       * @default
       */
      product_package_name?: string;
      /**
       * Giá tiền của gói sản phẩm 
       * @default 0
       */
      price?: number;
      /**
       * Danh sách định danh học viên được mua hộ 
       * @default []
       */
      user_names_list?: (components["schemas"]["UserByIDOrName"])[];
      /**
       * Nếu click thanh toán từ giỏ hàng thì có thêm thông tin này 
       * @default
       */
      cart_item_id?: string;
      /**
       * Tổng tiền theo từng gói sản phẩm 
       * @default 0
       */
      package_total_amount?: number;
    };
    /** R */
    R: {
      /**
       * Mã lỗi của hệ thống 1: SUCCESS; khác 1 là thất bại, Nếu thất bại thì message trả về thông báo lỗi. Thành công sẽ có data, data có cấu trúc Json hoặc JsonArray 
       * @default 1
       */
      status?: number;
      /** Message trả về khi có thông báo lỗi hoặc thành công mà muốn nhận message từ phía server */
      message?: string;
      /** Data được trả vể khi nghiệp vụ cần có dữ liệu xử lý */
      data?: unknown;
    };
    /** R[AddItemToCartResp] */
    R_AddItemToCartResp_: {
      /**
       * Mã lỗi của hệ thống 1: SUCCESS; khác 1 là thất bại, Nếu thất bại thì message trả về thông báo lỗi. Thành công sẽ có data, data có cấu trúc Json hoặc JsonArray 
       * @default 1
       */
      status?: number;
      /** Message trả về khi có thông báo lỗi hoặc thành công mà muốn nhận message từ phía server */
      message?: string;
      /** Data được trả vể khi nghiệp vụ cần có dữ liệu xử lý */
      data?: components["schemas"]["AddItemToCartResp"];
    };
    /** R[CartDetailReps] */
    R_CartDetailReps_: {
      /**
       * Mã lỗi của hệ thống 1: SUCCESS; khác 1 là thất bại, Nếu thất bại thì message trả về thông báo lỗi. Thành công sẽ có data, data có cấu trúc Json hoặc JsonArray 
       * @default 1
       */
      status?: number;
      /** Message trả về khi có thông báo lỗi hoặc thành công mà muốn nhận message từ phía server */
      message?: string;
      /** Data được trả vể khi nghiệp vụ cần có dữ liệu xử lý */
      data?: components["schemas"]["CartDetailReps"];
    };
    /** R[CreatePaymentResp] */
    R_CreatePaymentResp_: {
      /**
       * Mã lỗi của hệ thống 1: SUCCESS; khác 1 là thất bại, Nếu thất bại thì message trả về thông báo lỗi. Thành công sẽ có data, data có cấu trúc Json hoặc JsonArray 
       * @default 1
       */
      status?: number;
      /** Message trả về khi có thông báo lỗi hoặc thành công mà muốn nhận message từ phía server */
      message?: string;
      /** Data được trả vể khi nghiệp vụ cần có dữ liệu xử lý */
      data?: components["schemas"]["CreatePaymentResp"];
    };
    /** R[DetailPaymentTransaction] */
    R_DetailPaymentTransaction_: {
      /**
       * Mã lỗi của hệ thống 1: SUCCESS; khác 1 là thất bại, Nếu thất bại thì message trả về thông báo lỗi. Thành công sẽ có data, data có cấu trúc Json hoặc JsonArray 
       * @default 1
       */
      status?: number;
      /** Message trả về khi có thông báo lỗi hoặc thành công mà muốn nhận message từ phía server */
      message?: string;
      /** Data được trả vể khi nghiệp vụ cần có dữ liệu xử lý */
      data?: components["schemas"]["DetailPaymentTransaction"];
    };
    /** R[ListProductPackagesResp] */
    R_ListProductPackagesResp_: {
      /**
       * Mã lỗi của hệ thống 1: SUCCESS; khác 1 là thất bại, Nếu thất bại thì message trả về thông báo lỗi. Thành công sẽ có data, data có cấu trúc Json hoặc JsonArray 
       * @default 1
       */
      status?: number;
      /** Message trả về khi có thông báo lỗi hoặc thành công mà muốn nhận message từ phía server */
      message?: string;
      /** Data được trả vể khi nghiệp vụ cần có dữ liệu xử lý */
      data?: components["schemas"]["ListProductPackagesResp"];
    };
    /** R[List[src.models.product_packages.ListProductPackagesResp]] */
    "R_List_src.models.product_packages.ListProductPackagesResp__": {
      /**
       * Mã lỗi của hệ thống 1: SUCCESS; khác 1 là thất bại, Nếu thất bại thì message trả về thông báo lỗi. Thành công sẽ có data, data có cấu trúc Json hoặc JsonArray 
       * @default 1
       */
      status?: number;
      /** Message trả về khi có thông báo lỗi hoặc thành công mà muốn nhận message từ phía server */
      message?: string;
      /** Data được trả vể khi nghiệp vụ cần có dữ liệu xử lý */
      data?: (components["schemas"]["ListProductPackagesResp"])[];
    };
    /** R[PaymentOrderResp] */
    R_PaymentOrderResp_: {
      /**
       * Mã lỗi của hệ thống 1: SUCCESS; khác 1 là thất bại, Nếu thất bại thì message trả về thông báo lỗi. Thành công sẽ có data, data có cấu trúc Json hoặc JsonArray 
       * @default 1
       */
      status?: number;
      /** Message trả về khi có thông báo lỗi hoặc thành công mà muốn nhận message từ phía server */
      message?: string;
      /** Data được trả vể khi nghiệp vụ cần có dữ liệu xử lý */
      data?: components["schemas"]["PaymentOrderResp"];
    };
    /** R[RemoveToCartResp] */
    R_RemoveToCartResp_: {
      /**
       * Mã lỗi của hệ thống 1: SUCCESS; khác 1 là thất bại, Nếu thất bại thì message trả về thông báo lỗi. Thành công sẽ có data, data có cấu trúc Json hoặc JsonArray 
       * @default 1
       */
      status?: number;
      /** Message trả về khi có thông báo lỗi hoặc thành công mà muốn nhận message từ phía server */
      message?: string;
      /** Data được trả vể khi nghiệp vụ cần có dữ liệu xử lý */
      data?: components["schemas"]["RemoveToCartResp"];
    };
    /** R[VerifyPaymentResponse] */
    R_VerifyPaymentResponse_: {
      /**
       * Mã lỗi của hệ thống 1: SUCCESS; khác 1 là thất bại, Nếu thất bại thì message trả về thông báo lỗi. Thành công sẽ có data, data có cấu trúc Json hoặc JsonArray 
       * @default 1
       */
      status?: number;
      /** Message trả về khi có thông báo lỗi hoặc thành công mà muốn nhận message từ phía server */
      message?: string;
      /** Data được trả vể khi nghiệp vụ cần có dữ liệu xử lý */
      data?: components["schemas"]["VerifyPaymentResponse"];
    };
    /** R[VoucherResp] */
    R_VoucherResp_: {
      /**
       * Mã lỗi của hệ thống 1: SUCCESS; khác 1 là thất bại, Nếu thất bại thì message trả về thông báo lỗi. Thành công sẽ có data, data có cấu trúc Json hoặc JsonArray 
       * @default 1
       */
      status?: number;
      /** Message trả về khi có thông báo lỗi hoặc thành công mà muốn nhận message từ phía server */
      message?: string;
      /** Data được trả vể khi nghiệp vụ cần có dữ liệu xử lý */
      data?: components["schemas"]["VoucherResp"];
    };
    /** RemoveItemRequest */
    RemoveItemRequest: {
      /**
       * Định danh Transaction
       * @default
       */
      product_transaction_id?: string;

      /**
       * Định danh gói sản phẩm 
       * @default
       */
      product_package_id?: string;
      /**
       * Định danh giỏ hàng trường này có giá trị khi click từ giỏ hàng 
       * @default
       */
      cart_id?: string;
      /**
       * Định danh người được mua hộ 
       * @default
       */
      student_id?: string;
    };
    /** RemoveToCartParams */
    RemoveToCartParams: {
      /**
       * Định danh giỏ hàng 
       * @default
       */
      cart_id?: string;
      /**
       * Định danh gói sản phẩm 
       * @default
       */
      product_package_id?: string;
      /**
       * Định danh học sinh được mua hộ 
       * @default
       */
      student_id?: string;
    };
    /** RemoveToCartResp */
    RemoveToCartResp: {
      /**
       * Định danh giỏ hàng(Nếu định danh giỏ hàng chưa có trong localstorage thì lưu lại) 
       * @default
       */
      cart_id?: string;
      /**
       * Tổng tiền thanh toán 
       * @default 0
       */
      total_amount?: number;
      /** Danh sách gói sản phẩm */
      product_packages: (components["schemas"]["ProductPackageResponse"])[];
    };
    /** UserByIDOrName */
    UserByIDOrName: {
      /** User Id */
      user_id: string;
      /** User Name */
      user_name?: string;
    };
    /** UserChangePasswordRequest */
    UserChangePasswordRequest: {
      /**
       * User name 
       * @default hcss
       */
      username?: string;
      /**
       * Password 
       * @default Hyper123456
       */
      password?: string;
      /**
       * Password 
       * @default Hyper1234567
       */
      new_password?: string;
      /**
       * Owner of this user 
       * @default TRANG_NGUYEN
       */
      owner_id?: string;
    };
    /** UserForgetPasswordRequest */
    UserForgetPasswordRequest: {
      /**
       * User name 
       * @default
       */
      username?: string;
      /**
       * Owner of this user 
       * @default TRANG_NGUYEN
       */
      owner_id?: string;
    };
    /** UserLoginRequest */
    UserLoginRequest: {
      /**
       * User name 
       * @default hcss
       */
      username?: string;
      /**
       * Password 
       * @default Hyper123456
       */
      password?: string;
      /**
       * Owner of this user 
       * @default TRANG_NGUYEN
       */
      owner_id?: string;
    };
    /** UserRefreshTokenRequest */
    UserRefreshTokenRequest: {
      /**
       * Refresh token to get new access token 
       * @default
       */
      refresh_token?: string;
      /**
       * Owner of this user 
       * @default TRANG_NGUYEN
       */
      owner_id?: string;
    };
    /** UserRegisterRequest */
    UserRegisterRequest: {
      /**
       * User type: List of [STUDENT; PARENT; TEACHER; COLLABORATOR; AGENT] 
       * @default [
       *   "STUDENT"
       * ]
       */
      user_type?: (string)[];
      /**
       * User name 
       * @default
       */
      username?: string;
      /**
       * Password 
       * @default
       */
      password?: string;
      /**
       * User email 
       * @default
       */
      email?: string;
      /**
       * User phone number 
       * @default
       */
      phone_number?: string;
      /**
       * Gender type: 0: female; 1: male; 2: unknown 
       * @default 2
       */
      gender?: number;
      /**
       * Birth date 
       * Format: date-time
       */
      birth_date?: string;
      /**
       * Family name 
       * @default
       */
      family_name?: string;
      /**
       * First name 
       * @default
       */
      forename?: string;
      /**
       * Country ID 
       * @default
       */
      country_id?: string;
      /**
       * Ethnic group ID 
       * @default
       */
      ethnic_group?: string;
      /**
       * Province ID 
       * @default
       */
      province_id?: string;
      /**
       * Province name 
       * @default
       */
      province_name?: string;
      /**
       * District ID 
       * @default
       */
      district_id?: string;
      /**
       * District name 
       * @default
       */
      district_name?: string;
      /**
       * School ID 
       * @default
       */
      school_id?: string;
      /**
       * School name 
       * @default
       */
      school_name?: string;
      /**
       * Class ID 
       * @default
       */
      class_id?: string;
      /**
       * Class Name 
       * @default
       */
      class_name?: string;
      /**
       * Grade ID 
       * @default
       */
      grade_id?: string;
      /**
       * Address user 
       * @default
       */
      address?: string;
      /**
       * Owner of this user 
       * @default TRANG_NGUYEN
       */
      owner_id?: string;
    };
    /** UserUpdateRequest */
    UserUpdateRequest: {
      /**
       * User type: List of [STUDENT; PARENT; TEACHER; COLLABORATOR; AGENT] 
       * @default [
       *   "STUDENT"
       * ]
       */
      user_type?: (string)[];
      /**
       * User email 
       * @default
       */
      email?: string;
      /**
       * User phone number 
       * @default
       */
      phone_number?: string;
      /**
       * Gender type: 0: female; 1: male; 2: unknown 
       * @default 2
       */
      gender?: number;
      /**
       * Birth date 
       * Format: date-time
       */
      birth_date?: string;
      /**
       * Family name 
       * @default
       */
      family_name?: string;
      /**
       * First name 
       * @default
       */
      forename?: string;
      /**
       * Country ID 
       * @default
       */
      country_id?: string;
      /**
       * Ethnic group ID 
       * @default
       */
      ethnic_group?: string;
      /**
       * Province ID 
       * @default
       */
      province_id?: string;
      /**
       * Province name 
       * @default
       */
      province_name?: string;
      /**
       * District ID 
       * @default
       */
      district_id?: string;
      /**
       * District name 
       * @default
       */
      district_name?: string;
      /**
       * School ID 
       * @default
       */
      school_id?: string;
      /**
       * School name 
       * @default
       */
      school_name?: string;
      /**
       * Class ID 
       * @default
       */
      class_id?: string;
      /**
       * Class Name 
       * @default
       */
      class_name?: string;
      /**
       * Grade ID 
       * @default
       */
      grade_id?: string;
      /**
       * Address user 
       * @default
       */
      address?: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VerifyPaymentRequest */
    VerifyPaymentRequest: {
      /**
       * Định danh của một giao dịch thanh toán 
       * @default
       */
      product_transaction_id?: string;
      /** Thông tin thanh toán */
      pay_info?: components["schemas"]["PayInfo"];
    };
    /** VerifyPaymentResponse */
    VerifyPaymentResponse: {
      /**
       * Định danh của một giao dịch thanh toán 
       * @default
       */
      product_transaction_id?: string;
      /**
       * Tổng tiền thanh toán 
       * @default 0
       */
      total_amount?: number;
      /**
       * Tổng tiền được giảm từ voucher 
       * @default 0
       */
      total_voucher_amount?: number;
      /**
       * Danh sách gói sản phẩm 
       * @default []
       */
      product_packages?: (components["schemas"]["ProductPackageResponse"])[];
      /** Thông tin thanh toán */
      pay_info?: components["schemas"]["PayInfo"];
    };
    /** VoucherResp */
    VoucherResp: {
      /**
       * Định danh voucher 
       * @default
       */
      voucher_id?: string;
      /**
       * Giá trị của voucher 
       * @default 0
       */
      value?: number;
      /**
       * Đơn vị tiền tệ 
       * @default VND
       */
      monetary_unit?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** Product Package List */
  product_package_list_product_get: {
    parameters: {
      query?: {
        page?: unknown;
        size?: unknown;
        group_name?: unknown;
      };
      header?: {
        "owner-id"?: string;
        "user-id"?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["R_List_src.models.product_packages.ListProductPackagesResp__"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Product Package Detail */
  get_product_package_detail_product_product_detail_get: {
    parameters: {
      query: {
        product_package_id: string;
      };
      header?: {
        "owner-id"?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["R_ListProductPackagesResp_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Users Login */
  users_login_user_login_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserLoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get User Info From Access Token */
  get_user_info_from_access_token_user_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Users Change Password */
  users_change_password_user_change_password_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Users Refresh Token */
  users_refresh_token_user_refresh_token_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRefreshTokenRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Users Register */
  users_register_user_register_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRegisterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Users Update */
  users_update_user_update_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Forget Password */
  forget_password_user_forget_password_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserForgetPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Search By Exam Number */
  search_by_exam_number_user_search_by_exam_number_get: {
    parameters: {
      query: {
        owner_id: string;
        exam_number: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Avatar Link */
  get_avatar_link_user_get_avatar_link_get: {
    parameters: {
      query: {
        owner_id: string;
        gender: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Users Register With Captcha */
  users_register_with_captcha_user_register_captcha_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRegisterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Forget Password Captcha */
  forget_password_captcha_user_forget_password_captcha_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserForgetPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Search Elastic Exam Number */
  search_elastic_exam_number_user_search_es_exam_number_get: {
    parameters: {
      query: {
        owner_id: string;
        exam_number: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Api Ping */
  api_ping_common_ping_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Get Countries */
  get_countries_common_get_countries_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Get Ethnics */
  get_ethnics_common_get_ethnics_get: {
    parameters: {
      query: {
        country_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Provinces */
  get_provinces_common_get_provinces_get: {
    parameters: {
      query: {
        country_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Districts */
  get_districts_common_get_districts_get: {
    parameters: {
      query: {
        country_id: string;
        province_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Schools */
  get_schools_common_get_schools_get: {
    parameters: {
      query: {
        country_id: string;
        province_id: string;
        district_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Prefix Media Url */
  get_prefix_media_url_common_get_prefix_media_url_get: {
    parameters: {
      query: {
        owner_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Callback */
  callback_payment_callback_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaymentCallRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["R"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Payment Transaction */
  create_payment_transaction_payment_post: {
    parameters: {
      header?: {
        "owner-id"?: string;
        "user-id"?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePaymentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["R_CreatePaymentResp_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Remove Item */
  remove_item_payment_remove_item_post: {
    parameters: {
      header?: {
        "owner-id"?: string;
        "user-id"?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RemoveItemRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["R_VerifyPaymentResponse_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Verify Payment */
  verify_payment_payment_verify_post: {
    parameters: {
      header?: {
        "owner-id"?: string;
        "user-id"?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyPaymentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["R_VerifyPaymentResponse_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Payment Order */
  create_payment_order_payment_order_post: {
    parameters: {
      header?: {
        "owner-id"?: string;
        "user-id"?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaymentOrderRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["R_PaymentOrderResp_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Detail Payment Transaction */
  detail_payment_transaction_payment_tran_id__get: {
    parameters: {
      header?: {
        "owner-id"?: string;
        "user-id"?: string;
      };
      path: {
        tran_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["R_DetailPaymentTransaction_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Details */
  get_details_cart__cart_id__get: {
    parameters: {
      header?: {
        "owner-id"?: string;
        "user-id"?: string;
      };
      path: {
        cart_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["R_CartDetailReps_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Remove Item */
  remove_item_cart_remove_item_post: {
    parameters: {
      header?: {
        "owner-id"?: string;
        "user-id"?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RemoveToCartParams"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["R_RemoveToCartResp_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Add To Cart */
  add_to_cart_cart_add_item_post: {
    parameters: {
      header?: {
        "owner-id"?: string;
        "user-id"?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddItemToCartParams"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["R_AddItemToCartResp_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Verify Voucher */
  verify_voucher_voucher_verify__code__get: {
    parameters: {
      header?: {
        "owner-id"?: string;
        "user-id"?: string;
      };
      path: {
        code: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["R_VoucherResp_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Apply Voucher */
  apply_voucher_voucher_apply_post: {
    parameters: {
      header?: {
        "owner-id"?: string;
        "user-id"?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplyVoucherReq"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["R_VoucherResp_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
